services:
  - type: web
    name: fastapi-backend
    env: docker
    plan: free
    autoDeploy: true
    region: frankfurt
    branch: main
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    rootDir: backend
